name: Update M3U Playlist

on:
  schedule:
    - cron: "0 3 * * *"   # Her gün sabah 03:00'te çalışır
  workflow_dispatch:       # Manuel tetikleme seçeneği

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Gerekli paketleri yükle
        run: pip install requests

      - name: Script çalıştır
        run: python check_links.py

      - name: Değişiklikleri commit et
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add playlist.m3u
          git commit -m "🔄 Otomatik playlist güncellendi" || echo "No changes"
          git push
